baseURL = "https://tahadraidia.com/"
languageCode = "en-us"
title = "Taha Draidia"
theme = "tahadraidia_theme_v2"

[params]
  authorName = "Taha Draidia"
  websiteDescription = "Security Research and Software Engineering"
  titleHeader1 = "Taha Draidia's Website"
  titleHeader2 = "Security Research and Software Engineering"
  [params.socials]
    github = "tahadraidia"
    linkedin = "tahadraidia"
    twitter = "tahadraidia"
    youtube = "tahadraidia"

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = false

  [markup.goldmark.renderer]
    unsafe= true